feeds:
  bloomberg-tech:
    feed:
      url: https://www.bloomberg.com/topics/tech
      title: 'Bloomberg Tech'
    selectors:
      item: .index-page__item
      headline: .index-page__headline
      link: .index-page__headline a
      date: .label-and-timestamp
    date_format: MMMM DD, YYYY
